meta_product_name : "Skallup"
meta_title : "Skallup - Perfectionnez-vous en ligne sur votre métier"
meta_description : "Apprennez à vous former sur les métiers du bricolage et devenez un expert dans votre domaine"
meta_image : "SK.png" # devrait exister dans `app/assets/images/`
